### ISSUE TITLE
Issues about trianing the networks

### ISSUE THREAD

**Issue by kxgong** [bcmi/SimTrans-Weak-Shot-Classification#2]
Hi, thanks for your great work that has inspired me a lot.
I have a few questions about reproducing the results:

The `train_GAN_similarity.py` for _SimNet_ suggests that the _SimNet_ should be initialized with the pre-trained model `pretrained/CUB/step0/pretrained_84.5.pth`. I am awared that you have provided this model and I have downloaded it. But I curious how can I acuqire this model on my own? Such as, training a _SimNet_ initialized with _ImageNet_-pretrained parameters using `train_GAN_similarity.py`?

**Comment by chenbys** [comment]
Following the procedure of _ICLR2018@Learning to cluster in order to transfer across domains and tasks_, the similarity net is  initialized by the the classifier pre-trained on base set.

**Comment by kxgong** [comment]
> Following the procedure of _ICLR2018@Learning to cluster in order to transfer across domains and tasks_, the similarity net is initialized by the the classifier pre-trained on base set.

Thanks. I will try this.
